server {
    listen *:80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
        gzip on;
        gzip_types text/css text/plain text/html text/javascript application/xml application/javascript application/json;
    }

    location /healthz {
        access_log off;
        return 200 "healthy\n";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
